datastax-java-driver:
  basic:
    contact-points: 127.0.0.1:9042


spring:
  kafka:
    bootstrap-servers: localhost:29093
    consumer:
      group-id: telemetry-consumer
      enable-auto-commit: false
    listener:
      ack-mode: manual_immediate

topic-to-consume-message: telemetry-topic

scylla:
  host: "127.0.0.1"
  port: 9042